
[package]
authors = ["zhiyuanzmj <260480378@qq.com>"]
edition = "2024"
name = "compiler-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["napi"]
napi = []

[dependencies]
napi = {version = "3.3.0", features = ["napi9"]}
napi-derive = "3.3.0"
oxc_parser = "0.96.0"
oxc_ast = "0.96.0"
oxc_allocator = "0.96.0"
oxc_span = "0.96.0"
oxc_ast_visit = "0.96.0"
oxc_traverse = "0.96.0"
oxc_semantic = "0.96.0"
oxc_codegen = "0.96.0"
phf = "0.13.1"

[dev-dependencies]
insta = "1.43.2"
criterion = "0.7.0"

[[bench]]
name = "bench"
harness = false

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
